/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calendario_Consultorio;

import JSON.JSON;
import Lista_citas.Panel_registrocita_1;
import Lista_citas.Ven_registrocita_1;
import com.toedter.calendar.JDayChooser;
import java.awt.Color;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.shaper.StandardButtonShaper;


/**
 *
 * @author Rafael
 */
public class Panel_calendario extends javax.swing.JPanel {

    /**
     * Creates new form NewJFrame
     */
    Cod_calendario logica;
    
    
    public Panel_calendario(int fil,int col,Object[][] citas) {               
        initComponents();
 
        
        this.jButton1.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());        
        logica=new Cod_calendario(fil,col,citas);                       
    }
    
    public Panel_calendario(){    //SOLO PARA PRUEBA
        initComponents();          
        this.jButton1.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        logica=Cod_calendario.main(null);
        
        JDayChooser aux=((JDayChooser)Calen1.getComponent(1));
        aux.setForeground(Color.green);       
        
        
        
        System.out.println(
                (
                     aux.getDayPanel().getComponent(10).getClass()
                )
        );
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Calen1 = new com.toedter.calendar.JCalendar();

        setPreferredSize(new java.awt.Dimension(300, 300));

        jButton3.setText("jButton3");

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jButton2.setText("Calendario");
        jButton2.setDefaultCapable(false);
        jButton2.setFocusable(false);
        jButton2.setOpaque(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.setRolloverEnabled(false);
        jButton2.setSelected(true);
        jButton2.setVerifyInputWhenFocusTarget(false);

        Calen1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Calen1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Calen1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)))
        );
    }// </editor-fold>//GEN-END:initComponents
  
 public void refrescarCalendario(int fil,int col,Object[][] citas){     
      logica=new Cod_calendario(fil,col,citas);                       
    }
     public Object[] pruebacalen(){
    Date aux=Calen1.getDate();
    String day="";  
    Object retorno[];
    retorno = new Object[3];
        switch(aux.getDay()){
            case 0: day="Domingo";break;
            case 1: day="Lunes";break;
            case 2: day="Martes";break;
            case 3: day="Miercoles";break;
            case 4: day="Jueves";break;
            case 5: day="Viernes";break;
            case 6: day="Sabado";break;
            case 7: day="Domingo";break;            
        }       
        Object[][] mierda_para_cabral=null;
        try{
            mierda_para_cabral=logica.procesar_cita(aux); 
            
      
 
            
/* //IMPRIMIR LAS CITAS QUE MANDA A CABRAL
            for(int i=0;i<mierda_para_cabral.length;i++){  //imprimir fechas que le paso a cabral            
                for(int j=0;j<mierda_para_cabral[0].length;j++){
                   System.out.print(mierda_para_cabral[i][j]+" ");
                    
                }
            System.out.println();
            }
  */          
   /*        // IMPRIMIR TODAS LAS CITAS EN EL CALENDARIO
            for(int i=0;i<logica.tuplas.length;i++){  //imprimir fechas que le paso a cabral            
                for(int j=0;j<logica.tuplas[0].length;j++){
                   System.out.print(logica.tuplas[i][j]);
                    
                }
            System.out.println();
            }
    */        
  
        }catch(Exception ex){
            
            System.err.println("No hay citas en esa fecha "+ex);  
            Logger.getLogger(JSON.class.getName()).log(Level.SEVERE, null, ex);
            
            
            retorno[0]=day;
            retorno[1]=aux;
            retorno[2]=null;
            return retorno;
        }       
            retorno[0]=day;
            retorno[1]=aux;
            retorno[2]=mierda_para_cabral;
             
        return retorno;
    }
    

    
    
    private void PROBANDO(){
          
      for(int i=0;i<this.logica.fil;i++){
          for(int j=0;j<this.logica.col;j++)
              System.out.print(this.logica.tuplas[i][j]+" ");              
      System.out.println();
      }
      System.out.println();
      System.out.println("Diccionario");
      System.out.println();
      for(int i=0;i<this.logica.Diccionario.length;i++)
        System.out.println(this.logica.Diccionario[i]);
      
      System.out.println();
      System.out.println("Puntos");
      System.out.println();
      for(int i=0;i<this.logica.puntos.length;i++)
        System.out.println(this.logica.puntos[i]);
      
    }
    
    
    // aqui se le puede agregar alguito si quieres hacer otra cosa al precionar el boton del calendario
    // la verdadera accion la hace en PanelPrincipal
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //pruebacalen();
    }//GEN-LAST:event_jButton1ActionPerformed

    public JButton getjButton1(){
        return this.jButton1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JCalendar Calen1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
