/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package encuesta;

import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONException;

/**
 *
 * @author carlo
 */
public class pruebatesttryeso extends javax.swing.JFrame {

    /**
     * Creates new form pruebatesttryeso
     */
    public pruebatesttryeso() throws JSONException {
        
        initComponents();
        
       
      //  this.setPreferredSize(new Dimension(1000, 1100));
     //   this.setLayout(new BorderLayout());
       // addType type= new addType(123);
      //  this.add(type);
        
       // addQEnc qEnc= new addQEnc();
       // this.add(qEnc);
        
         //viewEnc vEnc= new viewEnc();
         //this.add(vEnc); 
       
        //pruebaApuntadorString();   inmutable
        //pruebaApuntadorArreglo();  los arreglos si guardan el apuntador al objeto arreglo 
        //pruebaImprimirMatriz();
        
        

    }

    
        void    pruebaImprimirMatriz()  {
          String[] asignador0= {"hueso","para los huesos"};
          String[] asignador1= {"cabeza","para los cabeza"};
          String[] asignador2= {"pierna","para los pierna"};
          String [][] asignador= {asignador0,asignador1,asignador2};
        
        System.out.print(asignador[0][0]);  System.out.print(" - ");  System.out.println(asignador[0][1]);
        System.out.print(asignador[1][0]);  System.out.print(" - ");  System.out.println(asignador[1][1]);
        System.out.print(asignador[2][0]);  System.out.print(" - ");  System.out.println(asignador[2][1]);
        }
    
        void    pruebaApuntadorString()  {
        String a= "casa";
        String b= "casa"; 
        String c= new String ("casa"); 
        if (a==c) {System.out.println(" 'a' es igual a 'c' ");}
        
        b = c;
        a=null; a=b;
        b="perro";
        if (a==b) {System.out.println(" 'a' es igual a 'b' ");}
        }
        
        
        void    pruebaApuntadorArreglo()  {
        String[] a = {"casa","perro", "aa"};
        String[] b = {"casa","perro", "sapo"};
        String[] c = {"casa","perro", "aa"};
        
        a=b;
        b[2]="caballo";
        
        System.out.println(a[2]);
        a[2]="tigre";
        System.out.println(b[2]);
        System.out.println(a[2]);
        if (a[1]==c[1]) {System.out.println(" 'a1' es igual a 'c1' ");}
        }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 200, 1000, 600));
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pruebatesttryeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pruebatesttryeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pruebatesttryeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pruebatesttryeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new pruebatesttryeso().setVisible(true);
                } catch (JSONException ex) {
                    Logger.getLogger(pruebatesttryeso.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
