/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulacion;


import com.sun.awt.AWTUtilities;
import java.awt.*;
import java.awt.geom.RoundRectangle2D;
import java.io.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import static simulacion.Simulacion.VentanaPrincipal;


/**
 *
 * @author Administrador
 */
public class Menu extends Framefondo {
     static   JButton boton = new JButton();
    /**
     * Creates new form Menu
     */
    static Home VentanaPrincipal = new Home();
    static Buscador_archivos buscador = new Buscador_archivos();
    private final PanelFondo p = new PanelFondo();
    static AcercaDe acerca = new AcercaDe();;
    
    public Menu() {
        initComponents();
//        this.setLocationRelativeTo(null);
//        
       
//        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        setBounds(100, 100, 450, 300);
//        
//        
//       
////        p.setBorder(new EmptyBorder(5, 5, 5, 5));
////        p.setLayout(new BorderLayout(0, 0));
//       
//        setContentPane(p);
//        
//        
//        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30); 
//        
//        this.setWindowShape(this, forma); 
//        this.setSize(600,396); //ancho por largo
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JB_datospantalla = new javax.swing.JButton();
        JB_datosarchivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JB_acercade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        JB_datospantalla.setBackground(new java.awt.Color(255, 255, 255));
        JB_datospantalla.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        JB_datospantalla.setForeground(new java.awt.Color(2, 48, 142));
        JB_datospantalla.setText("Cargar datos por pantalla");
        JB_datospantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_datospantallaActionPerformed(evt);
            }
        });

        JB_datosarchivo.setBackground(new java.awt.Color(255, 255, 255));
        JB_datosarchivo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        JB_datosarchivo.setForeground(new java.awt.Color(2, 48, 142));
        JB_datosarchivo.setText("Cargar Datos Desde Archivo");
        JB_datosarchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_datosarchivoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Simulación de Inventario");

        JB_acercade.setBackground(new java.awt.Color(255, 255, 255));
        JB_acercade.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        JB_acercade.setForeground(new java.awt.Color(2, 48, 142));
        JB_acercade.setText("Acerca De");
        JB_acercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_acercadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JB_datosarchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JB_datospantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JB_acercade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(JB_datosarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(JB_datospantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_acercade, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_datospantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_datospantallaActionPerformed
        this.dispose();
        VentanaPrincipal.setVisible(true);
    }//GEN-LAST:event_JB_datospantallaActionPerformed

    private void JB_datosarchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_datosarchivoActionPerformed
        this.dispose();
        buscador.archivo();

    }//GEN-LAST:event_JB_datosarchivoActionPerformed

    private void JB_acercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_acercadeActionPerformed
        this.dispose();
        
//        ImageIcon icono = new ImageIcon("/simulacion/imagenes/homesin.png");
//        boton.setSize(50, 50);
//        boton.setIcon(icono);
//        boton.setBounds(900,200,350,50);
//        boton.setLocation(50, 500);
        
        acerca.setVisible(true);
    }//GEN-LAST:event_JB_acercadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // Menu menu = new Menu();
                
                //menu.setVisible(true);
//                new Menu().setVisible(true);
                Framefondo jf = new Menu();
                jf.setLocationRelativeTo(null);
                
                

//                jf.add(boton);
                jf.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_acercade;
    private javax.swing.JButton JB_datosarchivo;
    private javax.swing.JButton JB_datospantalla;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
