/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultorio_medico;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Rafael
 */
public class PanelPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipal
     */
    JPanel panelCalendario;
    JPanel panelLista;
    JPanel panelHistorial;
    JPanel panelRegistroCita;
    JButton botonCalen;
    
    JButton botonLista;
    
    JButton botonHist;
    
    JButton botonRegis;
    
    public PanelPrincipal() {
        initComponents();
        botonCalen = new JButton();
         botonLista = new JButton();
          botonHist = new JButton();
           botonRegis = new JButton();
           
     
                   
                   
           
        
              botonCalen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalenActionPerformed(evt);
            }

       
        });
                 botonLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaActionPerformed(evt);
            }

           
        });
                    botonHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHistActionPerformed(evt);
            }

     
        });
          
             botonRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegisActionPerformed(evt);
            }

          
        });
             
             
             
           
        panelCalendario = new JPanel();
        panelLista = new JPanel();
        panelHistorial = new JPanel();
        panelRegistroCita = new JPanel();
        //Back
        panelCalendario.setBackground(Color.red);
        
        panelLista.setBackground(Color.black);
        
        panelHistorial.setBackground(Color.GREEN);
        
        panelRegistroCita.setBackground(Color.YELLOW);
        //Posiciono este beta
        panelCalendario.setBounds(0, 0, 400, 250);
        panelLista.setBounds(0, 251, 400,250);
        panelHistorial.setBounds(401, 0, 400, 500);
       // panelRegistroCita.setBounds(402,251,400,250);    
        
        
        
        // add buton
        panelCalendario.add(botonCalen);
        
        panelLista.add(botonLista);
        
        panelHistorial.add(botonHist);
        
        panelRegistroCita.add(botonRegis);
        
              botonCalen.setBounds(0, 0, 50, 50);
           botonLista.setBounds(0, 0, 50, 50);
           botonHist.setBounds(0, 0, 50, 50);
           botonRegis.setBounds(0, 0, 50, 50);
           
                  botonCalen.setVisible(true);
           botonLista.setVisible(true);
           botonHist.setVisible(true);
           botonRegis.setVisible(true);
             botonCalen.setText("ok");
        botonCalen.setDefaultCapable(false);
          botonLista.setText("ok");
        botonLista.setDefaultCapable(false);
        
          botonHist.setText("ok");
        botonHist.setDefaultCapable(false);
        
          botonRegis.setText("ok");
        botonRegis.setDefaultCapable(false);
        
        

           
           panelCalendario.setVisible(true);
                   panelLista.setVisible(true);
                   panelHistorial.setVisible(true);
                           panelRegistroCita.setVisible(true);
        
        this.add(panelCalendario);
        this.add(panelLista);
        this.add(panelHistorial);
        //this.add(panelRegistroCita);
        
    }
     private void botonCalenActionPerformed(ActionEvent evt) {
                 this.panelHistorial.setVisible(true);
                 }
     
      private void botonListaActionPerformed(ActionEvent evt) {
             this.panelHistorial.setVisible(false);
                 }
      
             private void botonHistActionPerformed(ActionEvent evt) {
               
            }
             
               private void botonRegisActionPerformed(ActionEvent evt) {
                }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
