/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calendario_Consultorio;

import java.util.Date;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.shaper.StandardButtonShaper;

/**
 *
 * @author Nico
 */
public class Ven_calendarioPanel extends javax.swing.JPanel {

    /**
     * Creates new form Ven_calendarioPanel
     */
        Cod_calendario logica;
    
   
    public Ven_calendarioPanel(int fil,int col,Object[][] citas) {               
        initComponents();               
        this.jButton1.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());        
        logica=new Cod_calendario(fil,col,citas);                       
    }
    
    public Ven_calendarioPanel(){    //SOLO PARA PRUEBA
        initComponents();          
        this.jButton1.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        logica=Cod_calendario.main(null);
    }
    
    void pruebacalen(){
    Date aux=Calen1.getDate();
    String day="";                
        switch(aux.getDay()){
            case 0: day="Domingo";break;
            case 1: day="Lunes";break;
            case 2: day="Martes";break;
            case 3: day="Miercoles";break;
            case 4: day="Jueves";break;
            case 5: day="Viernes";break;
            case 6: day="Sabado";break;
            case 7: day="Domingo";break;            
        }       
        Object[][] mierda_para_cabral=null;
        try{
            mierda_para_cabral=logica.procesar_cita(aux); 
            
        }catch(Exception ex){
            System.err.println("No hay citas en esa fecha "+ex);             
        }
        llamar_cabral(day, aux,mierda_para_cabral);
            //System.out.println(aux);

            /*for(int i=0;i<mierda_para_cabral.length;i++){  //imprimir fechas que le paso a cabral            
                for(int j=0;j<mierda_para_cabral[0].length;j++){
                    System.out.print(mierda_para_cabral[i][j]+" ");
                }
            System.out.println();
            }
            */
                             
        
    }
    private void llamar_cabral(String day, Date aux, Object[][] mierda_para_cabral) {
//            Proyecto.Switch.cambiar_vent(new Ven_registrocita_1());
           /* Proyecto.Switch.cambiar_vent(new Ven_registrocita_1(  //Constructor que debemos utilizar
                                                                         day,           //el dia si te pierdes puede mirar arriba cabron
                                                                         aux.getDate(), // numero del dia
                                                                         aux.getMonth()+1, // numero del mes
                                                                         aux.getYear()+1900,// numero del año
                                                                         mierda_para_cabral)// tabla con las tuplas que te importan         
                                        );
            
            Prueba pru= new Prueba(  //Constructor que debemos utilizar
                                                                         day,           //el dia si te pierdes puede mirar arriba cabron
                                                                         aux.getDate(), // numero del dia
                                                                         aux.getMonth()+1, // numero del mes
                                                                         aux.getYear()+1900,// numero del año
                                                                         mierda_para_cabral// tabla con las tuplas que te importan         
                                        );*/
            

            
        }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Calen1 = new com.toedter.calendar.JCalendar();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        Calen1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jButton2.setText("Calendario");
        jButton2.setDefaultCapable(false);
        jButton2.setFocusable(false);
        jButton2.setOpaque(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.setRolloverEnabled(false);
        jButton2.setSelected(true);
        jButton2.setVerifyInputWhenFocusTarget(false);

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Calen1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(132, 132, 132)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Calen1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pruebacalen();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar Calen1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
